package Basic_Form;

import Placeholder.TextPrompt;

public class FormLabel extends javax.swing.JFrame {
    
    public FormLabel() {
        initComponents();
        TextPrompt textprompt = new TextPrompt("I like coding on the beach...", TextAra_Placeholder);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        Title_label = new javax.swing.JLabel();
        SubTitle_label = new javax.swing.JLabel();
        Email_Label = new javax.swing.JLabel();
        InputLastName = new javax.swing.JTextField();
        InputName = new javax.swing.JTextField();
        InputPassword = new javax.swing.JTextField();
        InputEmail = new javax.swing.JTextField();
        FirstName_Label = new javax.swing.JLabel();
        LastName_Label = new javax.swing.JLabel();
        Password_Label = new javax.swing.JLabel();
        SectionSeparator = new javax.swing.JSeparator();
        TemsAndConditions = new javax.swing.JCheckBox();
        BusinessAcount = new javax.swing.JRadioButton();
        PersonalAcount = new javax.swing.JRadioButton();
        SectionSeparator1 = new javax.swing.JSeparator();
        Age_Label = new javax.swing.JLabel();
        SpinerAge = new javax.swing.JSpinner();
        Bio = new javax.swing.JLabel();
        Combobox = new javax.swing.JComboBox<>();
        Selection1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextAra_Placeholder = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main.setBackground(new java.awt.Color(27, 27, 50));
        Main.setForeground(new java.awt.Color(245, 246, 247));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Title_label.setFont(new java.awt.Font("JetBrains Mono NL", 0, 24)); // NOI18N
        Title_label.setForeground(new java.awt.Color(245, 246, 247));
        Title_label.setText("Registration Form");
        Main.add(Title_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 42, -1, -1));

        SubTitle_label.setFont(new java.awt.Font("JetBrains Mono NL", 0, 18)); // NOI18N
        SubTitle_label.setForeground(new java.awt.Color(245, 246, 247));
        SubTitle_label.setText("Place fill out this form with the required information");
        SubTitle_label.setToolTipText("");
        Main.add(SubTitle_label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 81, -1, -1));

        Email_Label.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        Email_Label.setForeground(new java.awt.Color(245, 246, 247));
        Email_Label.setText("Enter Your Email: ");
        Main.add(Email_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 207, -1, -1));

        InputLastName.setBackground(new java.awt.Color(10, 10, 35));
        InputLastName.setForeground(new java.awt.Color(245, 246, 247));
        InputLastName.setBorder(null);
        Main.add(InputLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 156, 226, 33));

        InputName.setBackground(new java.awt.Color(10, 10, 35));
        InputName.setForeground(new java.awt.Color(245, 246, 247));
        InputName.setBorder(null);
        Main.add(InputName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 156, 226, 33));

        InputPassword.setBackground(new java.awt.Color(10, 10, 35));
        InputPassword.setForeground(new java.awt.Color(245, 246, 247));
        InputPassword.setBorder(null);
        Main.add(InputPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 233, 226, 33));

        InputEmail.setBackground(new java.awt.Color(10, 10, 35));
        InputEmail.setForeground(new java.awt.Color(245, 246, 247));
        InputEmail.setBorder(null);
        Main.add(InputEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 233, 226, 33));

        FirstName_Label.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        FirstName_Label.setForeground(new java.awt.Color(245, 246, 247));
        FirstName_Label.setText("Enter Your First Name: ");
        Main.add(FirstName_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 118, -1, -1));

        LastName_Label.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        LastName_Label.setForeground(new java.awt.Color(245, 246, 247));
        LastName_Label.setText("Enter Your Last Name: ");
        Main.add(LastName_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 118, -1, -1));

        Password_Label.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        Password_Label.setForeground(new java.awt.Color(245, 246, 247));
        Password_Label.setText("Create a New Password: ");
        Main.add(Password_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 207, -1, -1));

        SectionSeparator.setBackground(new java.awt.Color(59, 59, 79));
        SectionSeparator.setForeground(new java.awt.Color(59, 59, 79));
        Main.add(SectionSeparator, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 284, 594, 14));

        TemsAndConditions.setBackground(new java.awt.Color(27, 27, 50));
        TemsAndConditions.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        TemsAndConditions.setForeground(new java.awt.Color(246, 246, 247));
        TemsAndConditions.setText("I accept the terms and conditions");
        TemsAndConditions.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TemsAndConditionsActionPerformed(evt);
            }
        });
        Main.add(TemsAndConditions, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 338, -1, -1));

        BusinessAcount.setBackground(new java.awt.Color(27, 27, 50));
        BusinessAcount.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        BusinessAcount.setForeground(new java.awt.Color(245, 246, 247));
        BusinessAcount.setText("Business Account");
        Main.add(BusinessAcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(293, 304, -1, -1));

        PersonalAcount.setBackground(new java.awt.Color(27, 27, 50));
        PersonalAcount.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        PersonalAcount.setForeground(new java.awt.Color(245, 246, 247));
        PersonalAcount.setText("Personal Account");
        Main.add(PersonalAcount, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 304, -1, -1));

        SectionSeparator1.setBackground(new java.awt.Color(59, 59, 79));
        SectionSeparator1.setForeground(new java.awt.Color(59, 59, 79));
        Main.add(SectionSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 374, 594, 14));

        Age_Label.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        Age_Label.setForeground(new java.awt.Color(245, 246, 247));
        Age_Label.setText("Input your age: ");
        Main.add(Age_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 394, -1, -1));

        SpinerAge.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        Main.add(SpinerAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 421, 216, 32));

        Bio.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        Bio.setForeground(new java.awt.Color(245, 246, 247));
        Bio.setText("Provide a bio:");
        Main.add(Bio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 473, -1, -1));

        Combobox.setBackground(new java.awt.Color(10, 10, 36));
        Combobox.setForeground(new java.awt.Color(245, 246, 247));
        Combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "(Select One)", "FreeCodeCamp News", "FreeCodeCamp Youtube Chanel", "FreeCodeCamp Forum", "Other", " " }));
        Main.add(Combobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 420, 216, 35));

        Selection1.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        Selection1.setForeground(new java.awt.Color(245, 246, 247));
        Selection1.setText("How did you hear about us?");
        Main.add(Selection1, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 394, -1, -1));

        TextAra_Placeholder.setBackground(new java.awt.Color(10, 10, 35));
        TextAra_Placeholder.setColumns(20);
        TextAra_Placeholder.setForeground(new java.awt.Color(245, 246, 247));
        TextAra_Placeholder.setRows(5);
        jScrollPane1.setViewportView(TextAra_Placeholder);

        Main.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 499, 480, -1));

        jButton1.setBackground(new java.awt.Color(59, 59, 79));
        jButton1.setFont(new java.awt.Font("JetBrains Mono NL", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(245, 246, 247));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Basic_Form/Resorces/salvado.png"))); // NOI18N
        jButton1.setText("Submit");
        Main.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 611, 230, 44));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Main, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TemsAndConditionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TemsAndConditionsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TemsAndConditionsActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLabel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLabel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Age_Label;
    private javax.swing.JLabel Bio;
    private javax.swing.JRadioButton BusinessAcount;
    private javax.swing.JComboBox<String> Combobox;
    private javax.swing.JLabel Email_Label;
    private javax.swing.JLabel FirstName_Label;
    private javax.swing.JTextField InputEmail;
    private javax.swing.JTextField InputLastName;
    private javax.swing.JTextField InputName;
    private javax.swing.JTextField InputPassword;
    private javax.swing.JLabel LastName_Label;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel Password_Label;
    private javax.swing.JRadioButton PersonalAcount;
    private javax.swing.JSeparator SectionSeparator;
    private javax.swing.JSeparator SectionSeparator1;
    private javax.swing.JLabel Selection1;
    private javax.swing.JSpinner SpinerAge;
    private javax.swing.JLabel SubTitle_label;
    private javax.swing.JCheckBox TemsAndConditions;
    private javax.swing.JTextArea TextAra_Placeholder;
    private javax.swing.JLabel Title_label;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
